{% set version = '0.9.5' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-tidysdm
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/tidysdm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/tidysdm/tidysdm_{{ version }}.tar.gz
  sha256: 88d04c8946b57bd982a70a278d065797537aab5971da34be8eca5691a8cafd6e

build:
  merge_build_host: True  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/
  missing_dso_whitelist:
    - '*/R.dll'        # [win]
    - '*/Rblas.dll'    # [win]
    - '*/Rlapack.dll'  # [win]

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-dalex
    - r-dalextra
    - r-dials
    - r-dplyr
    - r-ggplot2
    - r-lubridate
    - r-magrittr
    - r-maxnet
    - r-parsnip
    - r-patchwork
    - r-recipes
    - r-rlang >=1.0.0
    - r-rsample
    - r-sf
    - r-spatialsample
    - r-terra
    - r-tibble
    - r-tidymodels
    - r-tune
    - r-workflows
    - r-workflowsets
    - r-yardstick
  run:
    - r-base
    - r-dalex
    - r-dalextra
    - r-dials
    - r-dplyr
    - r-ggplot2
    - r-lubridate
    - r-magrittr
    - r-maxnet
    - r-parsnip
    - r-patchwork
    - r-recipes
    - r-rlang >=1.0.0
    - r-rsample
    - r-sf
    - r-spatialsample
    - r-terra
    - r-tibble
    - r-tidymodels
    - r-tune
    - r-workflows
    - r-workflowsets
    - r-yardstick

test:
  commands:
    - $R -e "library('tidysdm')"           # [not win]
    - "\"%R%\" -e \"library('tidysdm')\""  # [win]

about:
  home: https://github.com/EvolEcolGroup/tidysdm
  dev_url: https://evolecolgroup.github.io/tidysdm/
  license: AGPL-3.0-or-later
  summary: Fit species distribution models (SDMs) using the 'tidymodels' framework, which provides
    a standardised interface to define models and process their outputs. 'tidysdm' expands
    'tidymodels' by providing methods for spatial objects, models and metrics specific
    to SDMs, as well as a number of specialised functions to process occurrences for
    contemporary and palaeo datasets. The full functionalities of the package are described
    in Leonardi et al. (2023) <doi:10.1101/2023.07.24.550358>.
  license_family: AGPL
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/AGPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - dramanica

# Package: tidysdm
# Title: Species Distribution Models with Tidymodels
# Version: 0.9.5
# Authors@R: c( person("Michela", "Leonardi", role = "aut"), person("Margherita", "Colucci", role = "aut"), person("Andrea", "Pozzi", role = "aut"), person("Andrea", "Manica", , "am315@cam.ac.uk", role = c("aut", "cre")))
# Description: Fit species distribution models (SDMs) using the 'tidymodels' framework, which provides a standardised interface to define models and process their outputs. 'tidysdm' expands 'tidymodels' by providing methods for spatial objects, models and metrics specific to SDMs, as well as a number of specialised functions to process occurrences for contemporary and palaeo datasets. The full functionalities of the package are described in Leonardi et al. (2023) <doi:10.1101/2023.07.24.550358>.
# License: AGPL (>= 3)
# Encoding: UTF-8
# Language: en-GB
# URL: https://github.com/EvolEcolGroup/tidysdm, https://evolecolgroup.github.io/tidysdm/
# BugReports: https://github.com/EvolEcolGroup/tidysdm/issues
# RoxygenNote: 7.3.1
# Depends: tidymodels, spatialsample, R (>= 3.50)
# Imports: dials, DALEX, DALEXtra, dplyr, ggplot2, lubridate, magrittr, maxnet, methods, parsnip, patchwork, recipes, rsample, rlang (>= 1.0.0), stats, sf, terra, tibble, tune, workflows, workflowsets, yardstick
# Suggests: blockCV, data.table, doParallel, earth, kernlab, knitr, overlapping, pastclim (>= 2.0.0), ranger, rgbif, rmarkdown, spelling, stacks, testthat (>= 3.0.0), tidyterra, vdiffr, xgboost
# VignetteBuilder: knitr
# Config/testthat/edition: 3
# LazyData: true
# NeedsCompilation: no
# Packaged: 2024-06-23 19:12:20 UTC; andrea
# Author: Michela Leonardi [aut], Margherita Colucci [aut], Andrea Pozzi [aut], Andrea Manica [aut, cre]
# Maintainer: Andrea Manica <am315@cam.ac.uk>
# Repository: CRAN
# Date/Publication: 2024-06-23 19:40:02 UTC
